from mongoengine import *
import datetime, os
import configparser
from bson.objectid import ObjectId


config = configparser.ConfigParser()
dir_path = os.path.dirname(os.path.realpath(__file__))
config.read(dir_path+'/../config.ini')

# Mongo
mongodb = config['db']['mongodb']
mongoport = int(config['db']['mongoport'])
cve_collection = config['db']['cve_collection']
mongo_database = config['db']['mongodatabase']

connect(
    db=mongo_database,
    host=mongodb,
    port=mongoport
)

#Creating a collection and document schema

class cisco(Document):
    _id = ObjectIdField(default=ObjectId)
    rev_pld_var = FloatField()
    src_port = IntField()
    pld_distinct = IntField()
    rev_hdr_ccnt = ListField()
    bytes_out = IntField()
    hdr_mean = FloatField()
    rev_intervals_ccnt = ListField()
    time_length = FloatField()
    num_pkts_out = IntField()
    pld_ccnt = ListField()
    pld_mean = FloatField()
    rev_pld_distinct = IntField()
    num_pkts_in = IntField()
    hdr_distinct = IntField()
    rev_hdr_distinct = IntField()
    hdr_bin_40 = IntField()
    pr = IntField()
    pld_max = IntField()
    hdr_ccnt = ListField()
    rev_pld_max = IntField()
    ack_psh_rst_syn_fin_cnt = ListField()
    pld_bin_inf = IntField()
    rev_pld_mean = FloatField()
    pld_median = IntField()
    dst_port = IntField()
    sa = StringField()
    rev_pld_bin_128 = IntField()
    da = StringField()
    intervals_ccnt = ListField()
    rev_ack_psh_rst_syn_fin_cnt = ListField()
    rev_hdr_bin_40 = IntField()
    rev_pld_ccnt = ListField()
    bytes_in = IntField()
    id = StringField(required=True, unique=True)
    
class cid(Document):
    _id = ObjectIdField(default=ObjectId)
    ack_psh_rst_syn_fin_cnt = ListField()
    bytes_in = IntField()
    bytes_out = IntField()
    da = StringField()
    dns_answer_cnt = FloatField()
    dns_answer_ip = ListField()
    dns_answer_ttl = ListField()
    dns_query_class = ListField()
    dns_query_cnt FloatField()
    dns_query_name = ListField()
    dns_query_name_len = ListField()
    dns_query_type = ListField()
    dst_port = IntField()
    hdr_bin_40 = IntField()
    hdr_ccnt = ListField()
    hdr_distinct = IntField()
    hdr_mean = FloatField()
    http_code = FloatField()
    http_content_len = FloatField()
    http_content_type = ListField()
    http_host = ListField()
    http_method = FloatField()
    http_uri = ListField()
    intervals_ccnt = ListField()
    num_pkts_in = IntField()
    num_pkts_out = IntField()
    pld_bin_inf = IntField()
    pld_ccnt = ListField()
    pld_distinct = IntField()
    pld_max = IntField()
    pld_mean = FloatField()
    pld_median = IntField()
    pr = IntField()
    rev_ack_psh_rst_syn_fin_cnt = ListField()
    rev_hdr_bin_40 = IntField()
    rev_hdr_ccnt = ListField()
    rev_hdr_distinct = IntField()
    rev_intervals_ccnt = ListField()
    rev_pld_bin_128 = IntField()
    rev_pld_ccnt = ListField()
    rev_pld_distinct = IntField()
    rev_pld_max = IntField()
    rev_pld_mean = FloatField()
    rev_pld_var = FloatField()
    sa = StringField()
    src_port = IntField()
    time_length = FloatField()
    tls_cnt  = FloatField()
    tls_cs = ListField()
    tls_cs_cnt = FloatField()
    tls_ext_cnt = FloatField()
    tls_ext_types = ListField()
    tls_key_exchange_len = FloatField()
    tls_len = ListField()
    tls_svr_cnt = FloatField()
    tls_svr_cs = ListField()
    tls_svr_cs_cnt = FloatField()
    tls_svr_ext_cnt = FloatField()
    tls_svr_ext_types = ListField()
    tls_svr_key_exchange_len = FloatField()
    tls_svr_len = ListField()
    id = StringField(required=True, unique=True)
    

class nonvpn(Document):
    _id = ObjectIdField(default=ObjectId)
    pr = IntField()
    rev_intervals_ccnt = ListField()
    rev_pld_max = IntField()
    dst_port = IntField()
    num_pkts_in = IntField()
    pld_ccnt = ListField()
    rev_hdr_ccnt = ListField()
    rev_hdr_bin_40 = IntField()
    bytes_in = IntField()
    rev_ack_psh_rst_syn_fin_cnt = ListField()
    time_length = FloatField() 
    da = StringField()
    rev_pld_var = FloatField() 
    pld_mean = FloatField() 
    rev_pld_mean = FloatField()
    pld_median = IntField()
    src_port = IntField()
    rev_pld_bin_128 = IntField()
    sa = StringField()
    hdr_distinct = IntField()
    rev_pld_distinct = IntField()
    ack_psh_rst_syn_fin_cnt = ListField()
    pld_distinct = IntField()
    tls_svr_key_exchange_len = IntField()
    hdr_bin_40 = IntField()
    rev_pld_ccnt = ListField()
    tls_svr_cs_cnt = IntField()
    tls_key_exchange_len = IntField()
    tls_svr_ext_cnt = IntField()
    tls_svr_ext_types = ListField()
    tls_ext_cnt = IntField()
    tls_svr_cs = ListField()
    intervals_ccnt = ListField()
    hdr_ccnt = ListField()
    pld_bin_inf = IntField()
    tls_ext_types = ListField()
    hdr_mean = FloatField() 
    tls_len = ListField()
    tls_svr_len = ListField()
    num_pkts_out = IntField()
    tls_svr_cnt = IntField()
    tls_cs_cnt = IntField()
    tls_cs = ListField()
    rev_hdr_distinct = IntField()
    pld_max = IntField()
    tls_cnt = IntField()
    bytes_out = IntField()
    dns_answer_ip = ListField()
    http_uri = StringField()
    dns_answer_cnt = IntField()
    dns_query_name = ListField()
    dns_query_name_len = ListField()
    http_code = IntField()
    dns_query_type = ListField()
    http_host = StringField()
    dns_query_cnt = IntField()
    dns_query_class = ListField()
    http_content_type = StringField()
    http_content_len = IntField()
    dns_answer_ttl = ListField()
    http_method = IntField()
    label = StringField()
    id = StringField(required=True, unique=True)



