# This file will contains the docker installation and configuration commands applied to install mongodb
# Yum upgrade/update
# sudo yum install docker
# in this command we can find the volume and port mapping 

sudo docker run --name mongodb-cn -p 27017:27017 -v /home/mongodb/mongodata:/data/db:z mongo &
